### ISSUE TITLE
Add 50x50 lifeline sound

### ISSUE THREAD

**Issue by ua2004** [ua2004/Millionaire-3D#12]
Add 50x50 lifeline sound _"70 - Who Wants to Be a Millionaire - Fifty-Fifty.mp3"_. Background music must stop and start again after the lifeline sound is over.

https://youtu.be/riRyYPo6qMc?t=21m45s

**Comment by ua2004** [comment]
- [x] On questions 1-5 background music should not stop while using 50x50 lifeline. It is OK now.

- [ ] On questions 6-15 background music must stop and start again after the lifeline sound `70 - Who Wants to Be a Millionaire - Fifty-Fifty.mp3` is over.

https://youtu.be/riRyYPo6qMc?t=21m45s

**Comment by forestt** [comment]
At video linked below background music doesn't stop after using 50x50 lifeline despite the fact that questions number is 10. Is it something I did not understand?
https://youtu.be/riRyYPo6qMc?t=21m45s

**Comment by ua2004** [comment]
Hmm, actually you are right. I don't know why at first it seemed to me that the music was stopped. False alarm)
