### ISSUE TITLE
User can unselect his final answer

### ISSUE THREAD

**Issue by ua2004** [ua2004/Millionaire-3D#35]
![unselected answer](https://cloud.githubusercontent.com/assets/8424744/20916426/72c15174-bb94-11e6-887a-8c16bcc7e759.png)
When user selects a final answer and clicks on it again it becomes unselected. All answers must be unclickable after giving a final answer.

I suggest to create methods `LockAnswers`, `UnlockAnswers` and invoke them when user selects an answer and when a new question is displayed.

**Comment by forestt** [comment]
already fixed
