### ISSUE TITLE
Display "Total Prize Money" after giving wrong answer

### ISSUE THREAD

**Issue by ua2004** [ua2004/Millionaire-3D#4]
Add "Total Prize Money" after user finishes playing.

![image](https://cloud.githubusercontent.com/assets/8424744/14763918/ef5e26ec-09ad-11e6-8426-22043f86fabc.png)

**Comment by ua2004** [comment]
Could you make it look more like on the screenshot?

![image](https://cloud.githubusercontent.com/assets/8424744/20179866/ba9c9d70-a760-11e6-95cb-beed83903452.png)

Using [this](https://github.com/ua2004/Millionaire-3D/blob/master/Assets/Resources/Graphics/Classic/total_prize_bg_2.png) as background and `Logenze_question`. The font is `Copperplate Gothic Bold`, located in `fonts` folder.

**Comment by forestt** [comment]
ok, no problem.

**Comment by ua2004** [comment]
Nothing has changed. It should look like this (only after user gives wrong answer):

![image](https://cloud.githubusercontent.com/assets/8424744/20768628/47ea7bf2-b747-11e6-8c2c-e3e88e68fda2.png)
