### ISSUE TITLE
White diamonds are not displayed in money tree

### ISSUE THREAD

**Issue by ua2004** [ua2004/Millionaire-3D#7]
White diamonds are not displayed in money tree.

**Comment by ua2004** [comment]
Questions 1-9 should be on the same vertical line as 10-15.

![image](https://cloud.githubusercontent.com/assets/8424744/20766754/53073072-b740-11e6-9cf1-f119b8319cdb.png)
Like here:

![image](https://cloud.githubusercontent.com/assets/8424744/20766889/ce61e514-b740-11e6-9f5c-00faa0823fdd.png)

**Comment by forestt** [comment]
now it looks like this
![7](https://cloud.githubusercontent.com/assets/17526131/20859453/9e61f208-b968-11e6-844e-24d959125586.PNG)
